version: '3.8'

services:
  web_apptim:
    network_mode: host
    build:
        context: .
        dockerfile: Dockerfile
    container_name: web_apptim
    command: tail -F app
    volumes:
      - .:/usr/src/app
